INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgSend(typeUrl: send, from_address: a3, toAddress: a2, amount: 1))
INFO     authz:authz.py:21 Status:   OK
INFO     authz:authz.py:27 Expected: OK

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample10_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample10.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:83 ðŸ”¶ Step: request grant
INFO     authz:authz.py:87 request: MsgGrant(granter: a2, grantee: a3, msg: Grant(authorization: GenericAuthorization(msgTypeUrl: MsgTypeUrls.undelegate), expiration: ExpirationTime.past))
INFO     authz:authz.py:23 Status:   ERROR (code: 3, log: failed to execute message; message index: 0: expiration must be after the current block time (2022-10-26T13:53:58Z), got 2022-10-26T13:52:59Z: expiration time of authorization should be more than current time)
INFO     authz:authz.py:30 Expected: ERROR (expiration time of authorization should be more than current time)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a1, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample11_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample11.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a1, msg: MsgUndelegate(typeUrl: undelegate, delegatorAddress: a3, validatorAddress: v3, amount: -1))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample3_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample3.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a1, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a3, validatorSrcAddress: v1, validatorDstAddress: v3, amount: -1))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample2_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample2.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgSend(typeUrl: send, from_address: a3, toAddress: a3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 10, log: failed to execute message; message index: 0: failed to execute message; message from_address:"cosmos1s0qaahsgxrw8gsutgyuwzzn4x36yfz9nepdzzv" to_address:"cosmos1s0qaahsgxrw8gsutgyuwzzn4x36yfz9nepdzzv" amount:<denom:"stake" amount:"0" > : 0stake: invalid coins)
INFO     authz:authz.py:30 Expected: ERROR (invalid coins)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample9_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample9.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a1, msg: MsgSend(typeUrl: send, from_address: a3, toAddress: a3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample8_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample8.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a2, msgTypeUrl: MsgTypeUrls.send)
INFO     authz:authz.py:23 Status:   ERROR (code: 7, log: grantee and granter should be different)
INFO     authz:authz.py:30 Expected: ERROR (grantee and granter should be different)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample24_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample24.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a2, msgTypeUrl: MsgTypeUrls.undelegate)
INFO     authz:authz.py:23 Status:   ERROR (code: 7, log: grantee and granter should be different)
INFO     authz:authz.py:30 Expected: ERROR (grantee and granter should be different)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample25_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample25.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:83 ðŸ”¶ Step: request grant
INFO     authz:authz.py:87 request: MsgGrant(granter: a2, grantee: a2, msg: Grant(authorization: GenericAuthorization(msgTypeUrl: MsgTypeUrls.delegate), expiration: ExpirationTime.none))
INFO     authz:authz.py:23 Status:   ERROR (code: 7, log: grantee and granter should be different)
INFO     authz:authz.py:30 Expected: ERROR (grantee and granter should be different)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample17_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample17.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:83 ðŸ”¶ Step: request grant
INFO     authz:authz.py:87 request: MsgGrant(granter: a2, grantee: a1, msg: Grant(authorization: GenericAuthorization(msgTypeUrl: MsgTypeUrls.delegate), expiration: ExpirationTime.past))
INFO     authz:authz.py:23 Status:   ERROR (code: 3, log: failed to execute message; message index: 0: expiration must be after the current block time (2022-10-26T13:56:14Z), got 2022-10-26T13:55:14Z: expiration time of authorization should be more than current time)
INFO     authz:authz.py:30 Expected: ERROR (expiration time of authorization should be more than current time)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample16_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample16.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a1, msg: MsgDelegate(typeUrl: delegate, delegatorAddress: a3, validatorAddress: v2, amount: 1))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample4_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample4.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgUndelegate(typeUrl: undelegate, delegatorAddress: a3, validatorAddress: v2, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1s0qaahsgxrw8gsutgyuwzzn4x36yfz9nepdzzv" validator_address:"cosmosvaloper16afhu77sjs75kc78vylpnmg033seetk0lljcqg" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample5_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample5.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a2, msgTypeUrl: MsgTypeUrls.redelegate)
INFO     authz:authz.py:23 Status:   ERROR (code: 7, log: grantee and granter should be different)
INFO     authz:authz.py:30 Expected: ERROR (grantee and granter should be different)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample23_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample23.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a2, msgTypeUrl: MsgTypeUrls.delegate)
INFO     authz:authz.py:23 Status:   ERROR (code: 7, log: grantee and granter should be different)
INFO     authz:authz.py:30 Expected: ERROR (grantee and granter should be different)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample22_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample22.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a3, msgTypeUrl: MsgTypeUrls.delegate)
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample19_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample19.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a3, msgTypeUrl: MsgTypeUrls.send)
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample18_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample18.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:83 ðŸ”¶ Step: request grant
INFO     authz:authz.py:87 request: MsgGrant(granter: a2, grantee: a3, msg: Grant(authorization: GenericAuthorization(msgTypeUrl: MsgTypeUrls.delegate), expiration: ExpirationTime.past))
INFO     authz:authz.py:23 Status:   ERROR (code: 3, log: failed to execute message; message index: 0: expiration must be after the current block time (2022-10-26T13:58:24Z), got 2022-10-26T13:57:24Z: expiration time of authorization should be more than current time)
INFO     authz:authz.py:30 Expected: ERROR (expiration time of authorization should be more than current time)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgSend(typeUrl: send, from_address: a1, toAddress: a3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample13_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample13.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:83 ðŸ”¶ Step: request grant
INFO     authz:authz.py:87 request: MsgGrant(granter: a2, grantee: a3, msg: Grant(authorization: GenericAuthorization(msgTypeUrl: MsgTypeUrls.delegate), expiration: ExpirationTime.past))
INFO     authz:authz.py:23 Status:   ERROR (code: 3, log: failed to execute message; message index: 0: expiration must be after the current block time (2022-10-26T13:58:46Z), got 2022-10-26T13:57:46Z: expiration time of authorization should be more than current time)
INFO     authz:authz.py:30 Expected: ERROR (expiration time of authorization should be more than current time)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a1, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample12_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample12.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a3, validatorSrcAddress: v1, validatorDstAddress: v3, amount: -1))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1s0qaahsgxrw8gsutgyuwzzn4x36yfz9nepdzzv" validator_src_address:"cosmosvaloper126lcycn4tr3mlxfhtgd9lky5p3xpnjv90njne2" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"-1" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample1_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample1.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a3, msgTypeUrl: MsgTypeUrls.undelegate)
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample20_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample20.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:105 ðŸ”¶ Step: revoke grant
INFO     authz:authz.py:109 request: MsgRevoke(granter: a2, grantee: a3, msgTypeUrl: MsgTypeUrls.redelegate)
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a2, msg: MsgBeginRedelegate(typeUrl: redelegate, delegatorAddress: a2, validatorSrcAddress: v3, validatorDstAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 19, log: failed to execute message; message index: 0: failed to execute message; message delegator_address:"cosmos1kul5jtc8q8ahrjnpf2m05nwy20vafs0u27gesx" validator_src_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" validator_dst_address:"cosmosvaloper1st5sn8wf5wcqrdehy73n2ejq6ykhled9svamzt" amount:<denom:"stake" amount:"0" > : no delegation for (address, validator) tuple)
INFO     authz:authz.py:30 Expected: ERROR (failed to execute message)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample21_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample21.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:83 ðŸ”¶ Step: request grant
INFO     authz:authz.py:87 request: MsgGrant(granter: a2, grantee: a3, msg: Grant(authorization: GenericAuthorization(msgTypeUrl: MsgTypeUrls.delegate), expiration: ExpirationTime.past))
INFO     authz:authz.py:23 Status:   ERROR (code: 3, log: failed to execute message; message index: 0: expiration must be after the current block time (2022-10-26T14:00:07Z), got 2022-10-26T13:59:08Z: expiration time of authorization should be more than current time)
INFO     authz:authz.py:30 Expected: ERROR (expiration time of authorization should be more than current time)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgDelegate(typeUrl: delegate, delegatorAddress: a1, validatorAddress: v3, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample14_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample14.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:83 ðŸ”¶ Step: request grant
INFO     authz:authz.py:87 request: MsgGrant(granter: a2, grantee: a3, msg: Grant(authorization: GenericAuthorization(msgTypeUrl: MsgTypeUrls.delegate), expiration: ExpirationTime.past))
INFO     authz:authz.py:23 Status:   ERROR (code: 3, log: failed to execute message; message index: 0: expiration must be after the current block time (2022-10-26T14:00:29Z), got 2022-10-26T13:59:30Z: expiration time of authorization should be more than current time)
INFO     authz:authz.py:30 Expected: ERROR (expiration time of authorization should be more than current time)

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgUndelegate(typeUrl: undelegate, delegatorAddress: a1, validatorAddress: v2, amount: 0))
INFO     authz:authz.py:23 Status:   ERROR (code: 2, log: failed to execute message; authorization not found (UnicodeDecodeError))
INFO     authz:authz.py:30 Expected: ERROR (authorization not found)

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample15_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample15.itf.json
INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgDelegate(typeUrl: delegate, delegatorAddress: a3, validatorAddress: v3, amount: -1))
INFO     authz:authz.py:23 Status:   ERROR (code: 111222, log: recovered: negative coin amount: -1
stack:
goroutine 229 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x68
github.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x105f81620, 0x140011b4900})
	github.com/cosmos/cosmos-sdk/baseapp/recovery.go:71 +0x28
github.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x105f81620?, 0x140011b4900?})
	github.com/cosmos/cosmos-sdk/baseapp/recovery.go:39 +0x38
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x105f81620, 0x140011b4900}, 0x1400057a078?)
	github.com/cosmos/cosmos-sdk/baseapp/recovery.go:28 +0x3c
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x105f81620, 0x140011b4900}, 0x106278188?)
	github.com/cosmos/cosmos-sdk/baseapp/recovery.go:33 +0x64
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
	github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:602 +0xac
panic({0x105f81620, 0x140011b4900})
	runtime/panic.go:838 +0x204
github.com/cosmos/cosmos-sdk/types.NewCoin({0x14001235a60, 0x5}, {0x106278188?})
	github.com/cosmos/cosmos-sdk/types/coin.go:23 +0x54
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.Delegate({{0x106258dc0, 0x1400016a4a0}, {0x12e7a0f18, 0x14000ccfec0}, {0x10626ecf0, 0x14000f38460}, {0x12e7a0f88, 0x14000d52c60}, {0x106276af0, 0x1400057a180}, ...}, ...)
	github.com/cosmos/cosmos-sdk/x/staking/keeper/delegation.go:663 +0x998
github.com/cosmos/cosmos-sdk/x/staking/keeper.msgServer.Delegate({{{0x106258dc0, 0x1400016a4a0}, {0x12e7a0f18, 0x14000ccfec0}, {0x10626ecf0, 0x14000f38460}, {0x12e7a0f88, 0x14000d52c60}, {0x106276af0, 0x1400057a180}, ...}}, ...)
	github.com/cosmos/cosmos-sdk/x/staking/keeper/msg_server.go:234 +0x578
github.com/cosmos/cosmos-sdk/x/staking/types._Msg_Delegate_Handler.func1({0x10626b9f8, 0x140068ebc20}, {0x1061ca520?, 0x140068ec040})
	github.com/cosmos/cosmos-sdk/x/staking/types/tx.pb.go:810 +0x78
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x10626ca28, 0x140068f6b40}, {0x14006997dc8?, 0x104bad094?}, 0x106236580?, 0x140068cd260)
	github.com/cosmos/cosmos-sdk/baseapp/msg_service_router.go:113 +0xbc
github.com/cosmos/cosmos-sdk/x/staking/types._Msg_Delegate_Handler({0x10623fca0?, 0x14000c1b340}, {0x10626ca28, 0x140068f6b40}, 0x106245c78, 0x140068f8280)
	github.com/cosmos/cosmos-sdk/x/staking/types/tx.pb.go:812 +0x13c
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x10626b988, 0x1400005a090}, {0x106278188, 0x140068ecb40}, {{0xb, 0x0}, {0x14001041eb0, 0xb}, 0x2, {0x1b067118, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk/baseapp/msg_service_router.go:117 +0x254
github.com/cosmos/cosmos-sdk/x/authz/keeper.Keeper.DispatchActions({{0x106258dc0, 0x1400016a540}, {0x12e7a0f18, 0x14000ccfec0}, 0x1400057a060, {{0x106258dc0, 0x1400016a480}, {0x12e7a0f18, 0x14000ccfec0}, {{0x12e7a0f18, ...}, ...}, ...}}, ...)
	github.com/cosmos/cosmos-sdk/x/authz/keeper/keeper.go:141 +0x3f0
github.com/cosmos/cosmos-sdk/x/authz/keeper.Keeper.Exec({{0x106258dc0, 0x1400016a540}, {0x12e7a0f18, 0x14000ccfec0}, 0x1400057a060, {{0x106258dc0, 0x1400016a480}, {0x12e7a0f18, 0x14000ccfec0}, {{0x12e7a0f18, ...}, ...}, ...}}, ...)
	github.com/cosmos/cosmos-sdk/x/authz/keeper/msg_server.go:84 +0x24c
github.com/cosmos/cosmos-sdk/x/authz._Msg_Exec_Handler.func1({0x10626b9f8, 0x140068ebbf0}, {0x1061da3c0?, 0x140068ea300})
	github.com/cosmos/cosmos-sdk/x/authz/tx.pb.go:446 +0x78
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x10626ca28, 0x140068f6480}, {0x1400699a648?, 0x104bad094?}, 0x106236580?, 0x140068cd1e8)
	github.com/cosmos/cosmos-sdk/baseapp/msg_service_router.go:113 +0xbc
github.com/cosmos/cosmos-sdk/x/authz._Msg_Exec_Handler({0x1062053e0?, 0x1400024f500}, {0x10626ca28, 0x140068f6480}, 0x106245c78, 0x140068f8240)
	github.com/cosmos/cosmos-sdk/x/authz/tx.pb.go:448 +0x13c
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x10626b988, 0x1400005a090}, {0x106278188, 0x140068ecb40}, {{0xb, 0x0}, {0x14001041eb0, 0xb}, 0x2, {0x1b067118, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk/baseapp/msg_service_router.go:117 +0x254
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x10626b988, 0x1400005a090}, {0x106278188, 0x140068ecb40}, {{0xb, 0x0}, {0x14001041eb0, 0xb}, 0x2, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:743 +0x49c
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0x14000e76000, 0x3, {0x140052f6680, 0x199, 0x199})
	github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:688 +0x8c4
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(0x14000e76000, {{0x140052f6680?, 0x20?, 0xb?}})
	github.com/cosmos/cosmos-sdk/baseapp/abci.go:300 +0xf0
github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0x14000cd0900, {{0x140052f6680?, 0x14000cd0900?, 0x14005496308?}})
	github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:93 +0xf8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0x14006891680?, {{0x140052f6680?, 0x20?, 0xb?}})
	github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:85 +0x30
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x10626c9f0?, 0x14001002120}, {0x106271e08, 0x14000131270}, 0x14000fc43c0, {0x106277b10, 0x1400000f1b8}, 0x1?)
	github.com/tendermint/tendermint@v0.34.21/state/execution.go:320 +0x708
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x140011e09c0, 0x8}}, {0x140011e09d0, 0xb}, 0x1, 0x1, {{0x14000dafa20, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.21/state/execution.go:140 +0xe8
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x1400001d180, 0x2)
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1659 +0x954
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x1400001d180, 0x2)
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1568 +0x290
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1503 +0x94
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0x1400001d180, 0x2, 0x0)
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1541 +0xbc0
github.com/tendermint/tendermint/consensus.(*State).addVote(0x1400001d180, 0x140053ab860, {0x14000fee630, 0x28})
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:2155 +0xaf8
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x1400001d180, 0x140053ab860, {0x14000fee630?, 0x140005a3220?})
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1953 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0x1400001d180, {{0x106251df8?, 0x14000e72380?}, {0x14000fee630?, 0x0?}})
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:856 +0x3c0
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x1400001d180, 0x0)
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:763 +0x2d4
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:379 +0xf4
: panic)
INFO     authz:authz.py:30 Expected: ERROR (invalid delegation amount)

INFO     authz:authz.py:48 ðŸ”¶ Step: init
INFO     authz:authz.py:60 Preparing testnet...
INFO     authz:authz.py:65 Spining up testnet...
INFO     authz:authz.py:70 Wait for testnet to be ready...
INFO     authz:authz.py:74 Testnet launched! ðŸš€

INFO     authz:authz.py:129 ðŸ”¶ Step: execute grant
INFO     authz:authz.py:133 request: MsgExec(grantee: a3, msg: MsgDelegate(typeUrl: delegate, delegatorAddress: a3, validatorAddress: v3, amount: 1))
INFO     authz:authz.py:21 Status:   OK
INFO     authz:authz.py:27 Expected: OK

INFO     root:test_traces_authz_ExecuteWithoutGrants_sample6_itf_json.py:10 Successfully executed trace traces/authz/ExecuteWithoutGrants/sample6.itf.json
